drop function if exists poll_fn.get_poll_results(uuid, uuid, uuid, boolean);
drop function if exists poll_api.get_poll_results(uuid);
drop function if exists poll_fn.search_polls(poll_fn.search_polls_options, uuid);
drop function if exists poll_api.search_polls(poll_fn.search_polls_options);
drop function if exists poll_fn.save_response(uuid, poll_fn.answer_input[], uuid, boolean);
drop function if exists poll_api.submit_response(uuid, poll_fn.answer_input[]);
drop function if exists poll_api.save_response(uuid, poll_fn.answer_input[]);
drop function if exists poll_fn.delete_option(uuid, uuid, boolean);
drop function if exists poll_api.delete_option(uuid);
drop function if exists poll_fn.upsert_option(uuid, poll_fn.option_input, uuid, boolean);
drop function if exists poll_api.upsert_option(uuid, poll_fn.option_input);
drop function if exists poll_fn.delete_question(uuid, uuid, boolean);
drop function if exists poll_api.delete_question(uuid);
drop function if exists poll_fn.upsert_question(uuid, poll_fn.question_input, uuid, boolean);
drop function if exists poll_api.upsert_question(uuid, poll_fn.question_input);
drop function if exists poll_fn.delete_poll(uuid, uuid, boolean);
drop function if exists poll_api.delete_poll(uuid);
drop function if exists poll_fn.set_poll_status(uuid, poll.poll_status, uuid, boolean);
drop function if exists poll_api.set_poll_status(uuid, poll.poll_status);
drop function if exists poll_fn.set_poll_options(uuid, boolean, poll.results_visibility, uuid, boolean);
drop function if exists poll_api.set_poll_options(uuid, boolean, poll.results_visibility);
drop function if exists poll_fn.update_poll(uuid, citext, citext, timestamptz, uuid, boolean);
drop function if exists poll_api.update_poll(uuid, citext, citext, timestamptz);
drop function if exists poll_fn.create_poll(citext, citext, uuid);
drop function if exists poll_api.create_poll(citext, citext);
drop function if exists poll_fn.assert_draft(uuid);
drop function if exists poll_fn.assert_can_admin(uuid, uuid, boolean);
drop schema if exists poll_api;
