// ZITADEL OIDC client (stage 3 of .claude/specs/future-auth/zitadel-login-pattern.md).
//
// Decisions (a) — split-horizon issuer: the browser reaches ZITADEL at the external issuer
// (NUXT_ZITADEL_ISSUER, http://localhost:8200), but this container cannot. Server-side calls
// (token exchange, JWKS, userinfo) are rewritten to NUXT_ZITADEL_INTERNAL_URL while presenting
// the EXTERNAL host in the Host header — ZITADEL resolves its instance from Host, and the
// issued id_token `iss` must keep matching the external issuer. The rewrite uses node:http
// because undici's fetch silently strips a Host override (verified empirically).
//
// The clientId is generated by the zitadel-seed job and handed off via the shared volume
// (NUXT_ZITADEL_SEED_FILE) — never hardcoded.

import { readFile } from 'node:fs/promises'
import http from 'node:http'
import * as oidc from 'openid-client'

export type OidcContext = {
  config: oidc.Configuration
  clientId: string
  issuer: string
}

let cached: Promise<OidcContext> | null = null

export function getOidcContext(): Promise<OidcContext> {
  if (!cached) {
    cached = buildContext().catch((err) => {
      cached = null // don't cache failures (e.g. seed file not written yet)
      throw err
    })
  }
  return cached
}

async function buildContext(): Promise<OidcContext> {
  const rc = useRuntimeConfig()
  const issuer = requireConfig('zitadelIssuer', rc.zitadelIssuer)
  const internalUrl = requireConfig('zitadelInternalUrl', rc.zitadelInternalUrl)
  const seedFile = requireConfig('zitadelSeedFile', rc.zitadelSeedFile)

  const seed = JSON.parse(await readFile(seedFile, 'utf8')) as { clientId?: string }
  if (!seed.clientId) throw new Error(`oidc: no clientId in seed file ${seedFile}`)

  // Static metadata (ZITADEL's stable, documented endpoints) instead of discovery: the
  // discovery URL is the external issuer, unreachable from here, and this avoids a boot-order
  // dependency on ZITADEL being up.
  const config = new oidc.Configuration(
    {
      issuer,
      authorization_endpoint: `${issuer}/oauth/v2/authorize`,
      token_endpoint: `${issuer}/oauth/v2/token`,
      userinfo_endpoint: `${issuer}/oidc/v1/userinfo`,
      jwks_uri: `${issuer}/oauth/v2/keys`,
      end_session_endpoint: `${issuer}/oidc/v1/end_session`,
    },
    seed.clientId,
    {},
    oidc.None(), // public client — PKCE, no secret
  )

  if (issuer.startsWith('http://')) oidc.allowInsecureRequests(config) // dev only

  config[oidc.customFetch] = makeInternalFetch(new URL(issuer), new URL(internalUrl))

  return { config, clientId: seed.clientId, issuer }
}

function requireConfig(name: string, value: unknown): string {
  if (!value || typeof value !== 'string') throw new Error(`oidc: runtimeConfig.${name} is not set`)
  return value
}

// fetch-shaped transport that sends requests for the external issuer origin to the internal
// origin instead, with `Host: <external>` so ZITADEL resolves the right instance (the same
// pattern the official login container and docker/zitadel/seed.mjs use).
function makeInternalFetch(external: URL, internal: URL): typeof fetch {
  return ((input: string | URL, init?: RequestInit) => {
    const url = new URL(String(input))
    if (url.origin !== external.origin) return fetch(input as string, init)

    const headers: Record<string, string> = { host: external.host }
    new Headers((init?.headers as HeadersInit) ?? {}).forEach((v, k) => {
      headers[k] = v
    })
    headers.host = external.host

    const body =
      init?.body instanceof URLSearchParams ? init.body.toString() : (init?.body as string | undefined)
    if (body) headers['content-length'] = String(Buffer.byteLength(body))

    return new Promise<Response>((resolve, reject) => {
      const req = http.request(
        {
          hostname: internal.hostname,
          port: internal.port,
          path: url.pathname + url.search,
          method: init?.method ?? 'GET',
          headers,
        },
        (res) => {
          const chunks: Buffer[] = []
          res.on('data', (c: Buffer) => chunks.push(c))
          res.on('end', () => {
            const responseHeaders: Record<string, string> = {}
            for (const [k, v] of Object.entries(res.headers)) {
              if (typeof v === 'string') responseHeaders[k] = v
            }
            resolve(new Response(Buffer.concat(chunks), { status: res.statusCode, headers: responseHeaders }))
          })
        },
      )
      req.on('error', reject)
      if (body) req.write(body)
      req.end()
    })
  }) as typeof fetch
}
