drop function if exists todo_fn.deep_copy_todo(uuid, uuid, boolean, uuid);
drop function if exists todo_api.make_todo_from_template(uuid);
drop function if exists todo_api.make_template_from_todo(uuid);
drop function if exists todo_fn.search_todos(todo_fn.search_todos_options);
drop function if exists todo_api.search_todos(todo_fn.search_todos_options);
drop function if exists todo_fn.assign_todo(uuid, text);
drop function if exists todo_api.assign_todo(uuid, text);
drop function if exists todo_fn.unpin_todo(uuid);
drop function if exists todo_api.unpin_todo(uuid);
drop function if exists todo_fn.pin_todo(uuid);
drop function if exists todo_api.pin_todo(uuid);
drop function if exists todo_fn.delete_todo(uuid);
drop function if exists todo_api.delete_todo(uuid);
drop function if exists todo_fn.update_todo_status(uuid, todo.todo_status);
drop function if exists todo_api.update_todo_status(uuid, todo.todo_status);
drop function if exists todo_fn.update_todo(uuid, citext, citext);
drop function if exists todo_api.update_todo(uuid, citext, citext);
drop function if exists todo_fn.create_todo(citext, todo_fn.create_todo_options, uuid);
drop function if exists todo_api.create_todo(citext, todo_fn.create_todo_options);
