// Generated GraphQL types/hooks are an INTERNAL implementation detail — the barrel deliberately
// does NOT re-export the whole generated module. The UI's type vocabulary is `@function-bucket/
// fnb-types`; data flows through the composables below. Only the few generated urql hooks the UI
// genuinely needs as values are re-exported explicitly.
export { useDiscussionByIdQuery, useUpsertMessageMutation } from './generated/fnb-graphql-api'

export * from './composables/useProfileClaims'
export * from './composables/useResidency'
export * from './composables/useResource'
export * from './composables/useAdminLicenses'
export * from './composables/useAdminResidents'
export * from './composables/useAdminSubscriptions'
export * from './composables/useLocations'
export * from './composables/useMsgTopic'
export * from './composables/useMsgTopics'
export * from './composables/useSiteAdminApplications'
export * from './composables/useSiteAdminApplication'
export * from './composables/useSiteAdminTenants'
export * from './composables/useWorkspaces'
export * from './composables/useSiteAdminUsers'
export * from './composables/useSupportTickets'
export * from './composables/useSiteAssets'
export * from './composables/useAssetDetail'
export * from './composables/useSubjectAssets'
export * from './composables/useTodoList'
export * from './composables/useTodoDetail'
export * from './composables/useTodoMsg'
export * from './composables/useTriggerWorkflow'
export * from './composables/useN8nWorkflowRuns'
export * from './composables/useBreweries'
export * from './composables/useBrewery'
export * from './composables/useBreweryMapPoints'
export * from './composables/useAirports'
export * from './composables/useAirport'
export * from './composables/useAirportMapPoints'
export * from './composables/useGameTypes'
export * from './composables/useGames'
export * from './composables/useGame'
